
import { Product, User } from './types'

export const mockProducts: Product[] = [
  // Page 1 Products
  {
    id: '1',
    title: 'Advanced React Development Masterclass',
    description: 'Master React with hooks, context, and advanced patterns',
    fullDescription: 'Dive deep into React development with this comprehensive masterclass. Learn advanced hooks, context API, performance optimization, testing strategies, and modern React patterns. Build real-world projects and master the skills needed for senior React developer roles.',
    price: 750000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Modern%20software%20development%20course%20with%20React%20programming%20on%20computer%20screen%2C%20clean%20workspace%20with%20modern%20laptop%2C%20coding%20interface%2C%20vibrant%20pink%20and%20purple%20gradient%20background%2C%20professional%20educational%20setting%2C%20high%20quality%20digital%20art%2C%20modern%20minimalist%20design&width=400&height=300&seq=react-course-1&orientation=landscape',
    category: 'Programming',
    instructor: 'Sarah Johnson',
    rating: 4.8,
    reviewCount: 1247,
    duration: '32 hours',
    level: 'Advanced',
    tags: ['React', 'JavaScript', 'Frontend', 'Hooks', 'Context API']
  },
  {
    id: '2',
    title: 'AI & Machine Learning Fundamentals',
    description: 'Learn AI and ML from scratch with practical projects',
    fullDescription: 'Master the fundamentals of artificial intelligence and machine learning. Cover neural networks, deep learning, data preprocessing, model training, and deployment. Work on real-world projects including image recognition and natural language processing.',
    price: 1200000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Artificial%20intelligence%20and%20machine%20learning%20concept%20with%20neural%20networks%2C%20data%20visualization%2C%20algorithm%20diagrams%2C%20futuristic%20pink%20and%20blue%20gradient%20background%2C%20educational%20technology%2C%20clean%20modern%20design%2C%20high%20tech%20atmosphere&width=400&height=300&seq=ai-course-2&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Dr. Michael Chen',
    rating: 4.9,
    reviewCount: 892,
    duration: '45 hours',
    level: 'Intermediate',
    tags: ['AI', 'Machine Learning', 'Python', 'Neural Networks', 'Data Science']
  },
  {
    id: '3',
    title: 'Digital Marketing Strategy Course',
    description: 'Complete digital marketing from social media to SEO',
    fullDescription: 'Master digital marketing with comprehensive coverage of social media marketing, SEO, content marketing, email campaigns, and analytics. Learn to create effective marketing strategies and measure ROI across different channels.',
    price: 450000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Digital%20marketing%20strategy%20with%20social%20media%20icons%2C%20analytics%20charts%2C%20mobile%20devices%2C%20laptop%20showing%20marketing%20dashboard%2C%20pink%20and%20white%20professional%20background%2C%20modern%20business%20setting%2C%20clean%20minimalist%20design&width=400&height=300&seq=marketing-course-3&orientation=landscape',
    category: 'Marketing',
    instructor: 'Emma Williams',
    rating: 4.6,
    reviewCount: 634,
    duration: '28 hours',
    level: 'Beginner',
    tags: ['Marketing', 'SEO', 'Social Media', 'Analytics', 'Content Marketing']
  },
  {
    id: '4',
    title: 'UI/UX Design Principles & Practice',
    description: 'Master user interface and experience design',
    fullDescription: 'Learn comprehensive UI/UX design principles, user research methodologies, wireframing, prototyping, and design systems. Master tools like Figma and Adobe XD while building a professional design portfolio.',
    price: 680000,
    thumbnail: 'https://readdy.ai/api/search-image?query=UI%20UX%20design%20workspace%20with%20design%20tools%2C%20wireframes%2C%20color%20palettes%2C%20mobile%20mockups%2C%20tablet%20with%20design%20software%2C%20pink%20and%20purple%20gradient%20background%2C%20creative%20professional%20environment%2C%20modern%20design%20aesthetic&width=400&height=300&seq=design-course-4&orientation=landscape',
    category: 'Design',
    instructor: 'Alex Rodriguez',
    rating: 4.7,
    reviewCount: 756,
    duration: '35 hours',
    level: 'Intermediate',
    tags: ['UI Design', 'UX Design', 'Figma', 'Prototyping', 'User Research']
  },
  {
    id: '5',
    title: 'Full Stack Web Development Bootcamp',
    description: 'Complete web development from frontend to backend',
    fullDescription: 'Comprehensive bootcamp covering HTML, CSS, JavaScript, React, Node.js, databases, and deployment. Build multiple full-stack projects and learn industry best practices for modern web development.',
    price: 1500000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Full%20stack%20web%20development%20with%20multiple%20screens%20showing%20code%2C%20database%20schemas%2C%20server%20architecture%2C%20modern%20development%20setup%2C%20pink%20and%20blue%20tech%20background%2C%20professional%20coding%20environment%2C%20clean%20workspace&width=400&height=300&seq=fullstack-course-5&orientation=landscape',
    category: 'Programming',
    instructor: 'David Kim',
    rating: 4.8,
    reviewCount: 1123,
    duration: '60 hours',
    level: 'Beginner',
    tags: ['Full Stack', 'React', 'Node.js', 'JavaScript', 'Databases']
  },
  {
    id: '6',
    title: 'Data Visualization with D3.js',
    description: 'Create interactive data visualizations',
    fullDescription: 'Master data visualization with D3.js. Learn to create interactive charts, graphs, and dashboards. Cover data binding, animations, and advanced visualization techniques for compelling data storytelling.',
    price: 580000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Data%20visualization%20charts%20and%20graphs%20on%20computer%20screen%2C%20interactive%20dashboards%2C%20colorful%20data%20charts%2C%20analytics%20interface%2C%20pink%20and%20purple%20gradient%20background%2C%20modern%20data%20science%20workspace%2C%20professional%20setting&width=400&height=300&seq=dataviz-course-6&orientation=landscape',
    category: 'Programming',
    instructor: 'Lisa Zhang',
    rating: 4.5,
    reviewCount: 423,
    duration: '25 hours',
    level: 'Intermediate',
    tags: ['D3.js', 'Data Visualization', 'JavaScript', 'Charts', 'Analytics']
  },

  // Page 2 Products
  {
    id: '7',
    title: 'Python for Data Science',
    description: 'Master Python programming for data analysis and science',
    fullDescription: 'Comprehensive Python course focused on data science applications. Learn pandas, numpy, matplotlib, and scikit-learn. Work with real datasets and build predictive models.',
    price: 720000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Python%20programming%20for%20data%20science%20with%20code%20editor%2C%20data%20analysis%20charts%2C%20jupyter%20notebook%20interface%2C%20statistical%20graphs%2C%20pink%20and%20blue%20gradient%20background%2C%20modern%20data%20science%20workspace%2C%20clean%20professional%20setting&width=400&height=300&seq=python-course-7&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Dr. Jennifer Walsh',
    rating: 4.7,
    reviewCount: 934,
    duration: '40 hours',
    level: 'Beginner',
    tags: ['Python', 'Data Science', 'Pandas', 'NumPy', 'Machine Learning']
  },
  {
    id: '8',
    title: 'Mobile App Development with Flutter',
    description: 'Build cross-platform mobile apps with Flutter',
    fullDescription: 'Learn to build beautiful, fast mobile apps for iOS and Android using Flutter. Cover widgets, state management, navigation, and app deployment to app stores.',
    price: 850000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Mobile%20app%20development%20with%20Flutter%2C%20smartphone%20mockups%2C%20code%20editor%20with%20Dart%20language%2C%20app%20interfaces%2C%20pink%20and%20purple%20gradient%20background%2C%20modern%20mobile%20development%20workspace%2C%20clean%20design&width=400&height=300&seq=flutter-course-8&orientation=landscape',
    category: 'Programming',
    instructor: 'Carlos Martinez',
    rating: 4.6,
    reviewCount: 678,
    duration: '38 hours',
    level: 'Intermediate',
    tags: ['Flutter', 'Dart', 'Mobile Development', 'iOS', 'Android']
  },
  {
    id: '9',
    title: 'Brand Design & Visual Identity',
    description: 'Create compelling brand identities and visual systems',
    fullDescription: 'Master brand design from concept to execution. Learn logo design, color theory, typography, and brand guidelines. Build a comprehensive brand identity system.',
    price: 520000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Brand%20design%20workspace%20with%20logo%20sketches%2C%20color%20palettes%2C%20typography%20samples%2C%20brand%20guidelines%2C%20design%20tools%2C%20pink%20and%20white%20creative%20background%2C%20professional%20graphic%20design%20studio%2C%20modern%20aesthetic&width=400&height=300&seq=brand-course-9&orientation=landscape',
    category: 'Design',
    instructor: 'Sophie Laurent',
    rating: 4.8,
    reviewCount: 512,
    duration: '30 hours',
    level: 'Beginner',
    tags: ['Brand Design', 'Logo Design', 'Typography', 'Color Theory', 'Identity']
  },
  {
    id: '10',
    title: 'Content Marketing Mastery',
    description: 'Master content creation and marketing strategies',
    fullDescription: 'Learn to create engaging content that converts. Cover content strategy, storytelling, SEO writing, social media content, and performance measurement.',
    price: 380000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Content%20marketing%20with%20laptop%20showing%20blog%20editor%2C%20social%20media%20content%2C%20analytics%20dashboard%2C%20content%20calendar%2C%20pink%20and%20white%20marketing%20background%2C%20modern%20content%20creation%20workspace%2C%20professional%20setting&width=400&height=300&seq=content-course-10&orientation=landscape',
    category: 'Marketing',
    instructor: 'Tom Bradley',
    rating: 4.5,
    reviewCount: 445,
    duration: '24 hours',
    level: 'Beginner',
    tags: ['Content Marketing', 'SEO', 'Copywriting', 'Social Media', 'Strategy']
  },
  {
    id: '11',
    title: 'Deep Learning with TensorFlow',
    description: 'Advanced deep learning and neural network training',
    fullDescription: 'Master deep learning with TensorFlow. Build and train neural networks, work with image recognition, natural language processing, and deploy ML models.',
    price: 1350000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Deep%20learning%20with%20neural%20network%20visualizations%2C%20TensorFlow%20interface%2C%20GPU%20computing%2C%20AI%20algorithms%2C%20futuristic%20pink%20and%20blue%20background%2C%20advanced%20machine%20learning%20workspace%2C%20high%20tech%20environment&width=400&height=300&seq=tensorflow-course-11&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Dr. Raj Patel',
    rating: 4.9,
    reviewCount: 723,
    duration: '50 hours',
    level: 'Advanced',
    tags: ['Deep Learning', 'TensorFlow', 'Neural Networks', 'AI', 'Computer Vision']
  },
  {
    id: '12',
    title: 'JavaScript ES6+ Modern Development',
    description: 'Master modern JavaScript features and best practices',
    fullDescription: 'Learn modern JavaScript with ES6+ features. Cover async/await, modules, destructuring, arrow functions, and modern development tools and workflows.',
    price: 620000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Modern%20JavaScript%20development%20with%20code%20editor%2C%20ES6%20syntax%2C%20npm%20packages%2C%20webpack%20configuration%2C%20pink%20and%20purple%20coding%20background%2C%20professional%20web%20development%20workspace%2C%20clean%20modern%20design&width=400&height=300&seq=javascript-course-12&orientation=landscape',
    category: 'Programming',
    instructor: 'Jake Thompson',
    rating: 4.7,
    reviewCount: 856,
    duration: '35 hours',
    level: 'Intermediate',
    tags: ['JavaScript', 'ES6', 'Modern JS', 'Web Development', 'Programming']
  },

  // Page 3 Products
  {
    id: '13',
    title: 'Photoshop for Digital Artists',
    description: 'Master Adobe Photoshop for digital art and design',
    fullDescription: 'Complete Photoshop course for digital artists. Learn photo manipulation, digital painting, compositing, and advanced Photoshop techniques for creative projects.',
    price: 560000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Adobe%20Photoshop%20digital%20art%20workspace%20with%20graphics%20tablet%2C%20creative%20artwork%2C%20design%20tools%2C%20color%20palettes%2C%20pink%20and%20purple%20creative%20background%2C%20professional%20digital%20art%20studio%2C%20modern%20aesthetic&width=400&height=300&seq=photoshop-course-13&orientation=landscape',
    category: 'Design',
    instructor: 'Maya Chen',
    rating: 4.6,
    reviewCount: 689,
    duration: '32 hours',
    level: 'Beginner',
    tags: ['Photoshop', 'Digital Art', 'Photo Editing', 'Graphic Design', 'Creative']
  },
  {
    id: '14',
    title: 'Email Marketing Automation',
    description: 'Build automated email marketing campaigns that convert',
    fullDescription: 'Master email marketing automation. Learn to create email sequences, segment audiences, design responsive emails, and analyze campaign performance.',
    price: 420000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Email%20marketing%20automation%20with%20email%20templates%2C%20analytics%20dashboard%2C%20automation%20workflows%2C%20laptop%20with%20email%20campaign%2C%20pink%20and%20white%20marketing%20background%2C%20professional%20digital%20marketing%20workspace&width=400&height=300&seq=email-course-14&orientation=landscape',
    category: 'Marketing',
    instructor: 'Rachel Green',
    rating: 4.4,
    reviewCount: 378,
    duration: '22 hours',
    level: 'Intermediate',
    tags: ['Email Marketing', 'Automation', 'Marketing', 'Campaigns', 'Analytics']
  },
  {
    id: '15',
    title: 'Cloud Computing with AWS',
    description: 'Master Amazon Web Services cloud computing',
    fullDescription: 'Comprehensive AWS course covering EC2, S3, Lambda, databases, and cloud architecture. Learn to deploy and scale applications in the cloud.',
    price: 950000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Cloud%20computing%20with%20AWS%20services%2C%20server%20infrastructure%2C%20cloud%20architecture%20diagrams%2C%20data%20centers%2C%20pink%20and%20blue%20tech%20background%2C%20modern%20cloud%20computing%20workspace%2C%20professional%20IT%20environment&width=400&height=300&seq=aws-course-15&orientation=landscape',
    category: 'Programming',
    instructor: 'Mark Johnson',
    rating: 4.7,
    reviewCount: 654,
    duration: '42 hours',
    level: 'Intermediate',
    tags: ['AWS', 'Cloud Computing', 'DevOps', 'Infrastructure', 'Deployment']
  },
  {
    id: '16',
    title: 'Data Analysis with Excel & Power BI',
    description: 'Advanced data analysis and business intelligence',
    fullDescription: 'Master data analysis with Excel and Power BI. Learn advanced formulas, pivot tables, data modeling, and interactive dashboard creation.',
    price: 480000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Data%20analysis%20with%20Excel%20spreadsheets%2C%20Power%20BI%20dashboards%2C%20business%20charts%2C%20financial%20graphs%2C%20pink%20and%20white%20business%20background%2C%20professional%20data%20analysis%20workspace%2C%20clean%20office%20setting&width=400&height=300&seq=excel-course-16&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Linda Rodriguez',
    rating: 4.5,
    reviewCount: 567,
    duration: '28 hours',
    level: 'Beginner',
    tags: ['Excel', 'Power BI', 'Data Analysis', 'Business Intelligence', 'Dashboards']
  },
  {
    id: '17',
    title: 'Motion Graphics with After Effects',
    description: 'Create stunning motion graphics and animations',
    fullDescription: 'Master Adobe After Effects for motion graphics. Learn animation principles, visual effects, compositing, and create professional motion graphics projects.',
    price: 750000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Motion%20graphics%20with%20After%20Effects%20interface%2C%20animated%20elements%2C%20timeline%20editor%2C%20visual%20effects%2C%20pink%20and%20purple%20creative%20background%2C%20professional%20animation%20studio%2C%20modern%20creative%20workspace&width=400&height=300&seq=aftereffects-course-17&orientation=landscape',
    category: 'Design',
    instructor: 'Chris Park',
    rating: 4.8,
    reviewCount: 434,
    duration: '36 hours',
    level: 'Advanced',
    tags: ['After Effects', 'Motion Graphics', 'Animation', 'Visual Effects', 'Video']
  },
  {
    id: '18',
    title: 'Cybersecurity Fundamentals',
    description: 'Essential cybersecurity skills and practices',
    fullDescription: 'Learn cybersecurity fundamentals including network security, encryption, threat assessment, and security best practices for organizations.',
    price: 820000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Cybersecurity%20with%20security%20shields%2C%20network%20diagrams%2C%20encryption%20codes%2C%20firewall%20interfaces%2C%20pink%20and%20blue%20security%20background%2C%20professional%20cybersecurity%20workspace%2C%20high%20tech%20environment&width=400&height=300&seq=cybersec-course-18&orientation=landscape',
    category: 'Programming',
    instructor: 'Dr. Sarah Mitchell',
    rating: 4.6,
    reviewCount: 523,
    duration: '38 hours',
    level: 'Intermediate',
    tags: ['Cybersecurity', 'Network Security', 'Encryption', 'Security', 'IT']
  },

  // Page 4 Products
  {
    id: '19',
    title: 'Social Media Marketing Strategy',
    description: 'Master social media marketing across all platforms',
    fullDescription: 'Comprehensive social media marketing course. Learn platform-specific strategies, content creation, influencer marketing, and social media advertising.',
    price: 390000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Social%20media%20marketing%20with%20multiple%20platform%20icons%2C%20smartphone%20with%20social%20apps%2C%20engagement%20metrics%2C%20content%20creation%2C%20pink%20and%20white%20social%20background%2C%20modern%20social%20media%20workspace&width=400&height=300&seq=social-course-19&orientation=landscape',
    category: 'Marketing',
    instructor: 'Amy Foster',
    rating: 4.3,
    reviewCount: 398,
    duration: '26 hours',
    level: 'Beginner',
    tags: ['Social Media', 'Marketing', 'Content Creation', 'Advertising', 'Strategy']
  },
  {
    id: '20',
    title: 'Game Development with Unity',
    description: 'Create games with Unity game engine',
    fullDescription: 'Learn game development with Unity. Cover 2D and 3D game creation, scripting with C#, physics, animations, and game deployment.',
    price: 890000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Game%20development%20with%20Unity%20editor%2C%203D%20game%20scenes%2C%20character%20models%2C%20game%20assets%2C%20pink%20and%20purple%20gaming%20background%2C%20professional%20game%20development%20studio%2C%20modern%20creative%20workspace&width=400&height=300&seq=unity-course-20&orientation=landscape',
    category: 'Programming',
    instructor: 'Alex Turner',
    rating: 4.7,
    reviewCount: 712,
    duration: '44 hours',
    level: 'Intermediate',
    tags: ['Unity', 'Game Development', 'C#', '3D Graphics', 'Programming']
  },
  {
    id: '21',
    title: 'Illustration & Digital Art',
    description: 'Master digital illustration techniques and styles',
    fullDescription: 'Complete digital illustration course. Learn drawing fundamentals, digital painting techniques, character design, and illustration workflows.',
    price: 640000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Digital%20illustration%20with%20graphics%20tablet%2C%20artistic%20drawings%2C%20character%20designs%2C%20color%20palettes%2C%20pink%20and%20purple%20artistic%20background%2C%20professional%20digital%20art%20studio%2C%20creative%20workspace&width=400&height=300&seq=illustration-course-21&orientation=landscape',
    category: 'Design',
    instructor: 'Elena Rossi',
    rating: 4.8,
    reviewCount: 545,
    duration: '34 hours',
    level: 'Beginner',
    tags: ['Illustration', 'Digital Art', 'Drawing', 'Character Design', 'Creative']
  },
  {
    id: '22',
    title: 'Business Analytics & Intelligence',
    description: 'Data-driven business decision making',
    fullDescription: 'Master business analytics and intelligence. Learn statistical analysis, data mining, predictive modeling, and business intelligence tools.',
    price: 780000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Business%20analytics%20with%20financial%20charts%2C%20KPI%20dashboards%2C%20business%20intelligence%20reports%2C%20data%20analysis%2C%20pink%20and%20white%20business%20background%2C%20professional%20analytics%20workspace%2C%20modern%20office%20setting&width=400&height=300&seq=analytics-course-22&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Robert Kim',
    rating: 4.6,
    reviewCount: 467,
    duration: '40 hours',
    level: 'Intermediate',
    tags: ['Business Analytics', 'Data Mining', 'BI Tools', 'Statistics', 'Analysis']
  },
  {
    id: '23',
    title: 'E-commerce Marketing & Growth',
    description: 'Scale your e-commerce business with proven strategies',
    fullDescription: 'Complete e-commerce marketing course. Learn conversion optimization, email marketing, paid advertising, and growth hacking strategies.',
    price: 520000,
    thumbnail: 'https://readdy.ai/api/search-image?query=E-commerce%20marketing%20with%20online%20store%20interface%2C%20shopping%20cart%2C%20conversion%20analytics%2C%20product%20pages%2C%20pink%20and%20white%20e-commerce%20background%2C%20modern%20online%20business%20workspace&width=400&height=300&seq=ecommerce-course-23&orientation=landscape',
    category: 'Marketing',
    instructor: 'Jessica Wong',
    rating: 4.5,
    reviewCount: 356,
    duration: '30 hours',
    level: 'Intermediate',
    tags: ['E-commerce', 'Growth Marketing', 'Conversion', 'Online Business', 'Sales']
  },
  {
    id: '24',
    title: 'Blockchain Development',
    description: 'Build decentralized applications with blockchain',
    fullDescription: 'Learn blockchain development and smart contracts. Cover Ethereum, Solidity, Web3, and decentralized application development.',
    price: 1150000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Blockchain%20development%20with%20cryptocurrency%20symbols%2C%20smart%20contract%20code%2C%20blockchain%20network%2C%20decentralized%20systems%2C%20pink%20and%20blue%20crypto%20background%2C%20futuristic%20blockchain%20workspace%2C%20high%20tech%20environment&width=400&height=300&seq=blockchain-course-24&orientation=landscape',
    category: 'Programming',
    instructor: 'Michael Davis',
    rating: 4.8,
    reviewCount: 432,
    duration: '48 hours',
    level: 'Advanced',
    tags: ['Blockchain', 'Smart Contracts', 'Ethereum', 'Web3', 'DApp']
  },

  // Page 5 Products
  {
    id: '25',
    title: 'Video Editing with Premiere Pro',
    description: 'Professional video editing and post-production',
    fullDescription: 'Master Adobe Premiere Pro for professional video editing. Learn cutting techniques, color grading, audio editing, and video effects.',
    price: 680000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Video%20editing%20with%20Premiere%20Pro%20timeline%2C%20video%20clips%2C%20color%20grading%20panels%2C%20editing%20workspace%2C%20pink%20and%20purple%20creative%20background%2C%20professional%20video%20production%20studio%2C%20modern%20editing%20suite&width=400&height=300&seq=premiere-course-25&orientation=landscape',
    category: 'Design',
    instructor: 'Daniel Lee',
    rating: 4.7,
    reviewCount: 623,
    duration: '38 hours',
    level: 'Intermediate',
    tags: ['Premiere Pro', 'Video Editing', 'Post Production', 'Color Grading', 'Video']
  },
  {
    id: '26',
    title: 'Copywriting & Persuasive Writing',
    description: 'Write copy that sells and persuades',
    fullDescription: 'Master copywriting for marketing and sales. Learn persuasive writing techniques, sales psychology, and create high-converting copy.',
    price: 460000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Copywriting%20with%20laptop%20showing%20sales%20copy%2C%20marketing%20materials%2C%20writing%20tools%2C%20persuasive%20text%2C%20pink%20and%20white%20writing%20background%2C%20professional%20copywriting%20workspace%2C%20modern%20office%20setting&width=400&height=300&seq=copywriting-course-26&orientation=landscape',
    category: 'Marketing',
    instructor: 'Sarah Adams',
    rating: 4.6,
    reviewCount: 389,
    duration: '28 hours',
    level: 'Beginner',
    tags: ['Copywriting', 'Sales Writing', 'Marketing', 'Persuasion', 'Content']
  },
  {
    id: '27',
    title: 'iOS App Development with Swift',
    description: 'Build native iOS applications with Swift',
    fullDescription: 'Learn iOS app development with Swift. Cover UIKit, SwiftUI, Core Data, networking, and app store deployment.',
    price: 920000,
    thumbnail: 'https://readdy.ai/api/search-image?query=iOS%20app%20development%20with%20iPhone%20mockups%2C%20Xcode%20interface%2C%20Swift%20code%2C%20app%20UI%20screens%2C%20pink%20and%20purple%20mobile%20background%2C%20professional%20iOS%20development%20workspace%2C%20modern%20mobile%20studio&width=400&height=300&seq=ios-course-27&orientation=landscape',
    category: 'Programming',
    instructor: 'Kevin Chen',
    rating: 4.8,
    reviewCount: 567,
    duration: '45 hours',
    level: 'Intermediate',
    tags: ['iOS', 'Swift', 'Mobile Development', 'iPhone', 'App Development']
  },
  {
    id: '28',
    title: 'Statistical Analysis with R',
    description: 'Master statistical analysis and data science with R',
    fullDescription: 'Comprehensive R programming course for statistics and data science. Learn data manipulation, statistical modeling, and visualization.',
    price: 650000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Statistical%20analysis%20with%20R%20programming%2C%20statistical%20charts%2C%20data%20plots%2C%20RStudio%20interface%2C%20pink%20and%20blue%20analytics%20background%2C%20professional%20statistics%20workspace%2C%20data%20science%20environment&width=400&height=300&seq=r-course-28&orientation=landscape',
    category: 'AI & Data Science',
    instructor: 'Dr. Anna Wilson',
    rating: 4.5,
    reviewCount: 445,
    duration: '35 hours',
    level: 'Intermediate',
    tags: ['R Programming', 'Statistics', 'Data Science', 'Data Analysis', 'Modeling']
  },
  {
    id: '29',
    title: 'Web Design with Figma',
    description: 'Design beautiful websites and user interfaces',
    fullDescription: 'Master web design with Figma. Learn design systems, responsive design, prototyping, and handoff to developers.',
    price: 540000,
    thumbnail: 'https://readdy.ai/api/search-image?query=Web%20design%20with%20Figma%20interface%2C%20website%20mockups%2C%20design%20systems%2C%20UI%20components%2C%20pink%20and%20purple%20design%20background%2C%20professional%20web%20design%20workspace%2C%20modern%20design%20studio&width=400&height=300&seq=figma-course-29&orientation=landscape',
    category: 'Design',
    instructor: 'Lisa Park',
    rating: 4.7,
    reviewCount: 512,
    duration: '32 hours',
    level: 'Beginner',
    tags: ['Figma', 'Web Design', 'UI Design', 'Prototyping', 'Design Systems']
  },
  {
    id: '30',
    title: 'SEO & Google Analytics Mastery',
    description: 'Master search engine optimization and analytics',
    fullDescription: 'Complete SEO course covering keyword research, on-page optimization, link building, and Google Analytics for data-driven SEO.',
    price: 420000,
    thumbnail: 'https://readdy.ai/api/search-image?query=SEO%20and%20Google%20Analytics%20with%20search%20results%2C%20analytics%20dashboard%2C%20keyword%20research%20tools%2C%20ranking%20charts%2C%20pink%20and%20white%20SEO%20background%2C%20professional%20digital%20marketing%20workspace&width=400&height=300&seq=seo-course-30&orientation=landscape',
    category: 'Marketing',
    instructor: 'Mike Johnson',
    rating: 4.4,
    reviewCount: 467,
    duration: '30 hours',
    level: 'Beginner',
    tags: ['SEO', 'Google Analytics', 'Digital Marketing', 'Keywords', 'Analytics']
  }
]

export const mockUser: User = {
  id: 'user-1',
  name: 'John Doe',
  email: 'john@example.com',
  favoriteProducts: ['2', '4', '7'],
  viewedProducts: ['1', '2', '3', '4', '5']
}